### ISSUE TITLE
Crash on invalid serial

### ISSUE THREAD

**Issue by patto2k** [chilcote/warranty#4]
Got this crash on my machine that's unserialized.

machine:warranty service$ ./warranty 
Using this machine's serial number.
Serial number is not valid: None
Traceback (most recent call last):
  File "./warranty", line 193, in <module>
    main()
  File "./warranty", line 184, in main
    warranty.append([serial.upper(), model, str(date).split(' ')[0], status, asd])
AttributeError: 'NoneType' object has no attribute 'upper'

**Comment by chilcote** [comment]
Unserialized? As in, the logic board was replaced without re-serializing it?

**Comment by patto2k** [comment]
For posterity's sake the output of `/usr/sbin/ioreg -c IOPlatformExpertDevice -d 2` is:
````
Pat-MBP:~ service$ 
+-o Root  <class IORegistryEntry, id 0x100000100, retain 10>
  +-o MacBookPro8,2  <class IOPlatformExpertDevice, id 0x100000110, registered,$
      {
        "version" = <"1.0">
        "compatible" = <"MacBookPro8,2">
        "board-id" = <"Mac-94245A3940C91C80">
        "IOInterruptSpecifiers" = (<0900000005000000>)
        "IOPolledInterface" = "SMCPolledInterface is not serializable"
        "IOInterruptControllers" = ("io-apic-0")
        "IOPlatformUUID" = "0126378B-3523-57E9-B14C-929DCCB7BF0D"
        "clock-frequency" = <00e1f505>
        "IOPlatformSystemSleepPolicy" = <534c5054010006002000000020000000010000$
        "manufacturer" = <"Apple Inc.">
        "IOConsoleSecurityInterest" = "IOCommand is not serializable"
        "product-name" = <"MacBookPro8,2">
        "system-type" = <02>
        "model" = <"MacBookPro8,2">
        "name" = <"/">
        "IOBusyInterest" = "IOCommand is not serializable"
      }
